# Generated by Django 4.0.6 on 2022-07-18 01:57

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Pokemon Name')),
                ('height', models.IntegerField(verbose_name='Pokemon Height')),
                ('weight', models.IntegerField(verbose_name='Pokemon Weight')),
                ('stats', models.JSONField(verbose_name='Pokemon Stats')),
                ('evolution', models.JSONField(verbose_name='Pokemon Evolution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
