# Generated by Django 4.0.6 on 2022-07-18 03:47

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('request_url', models.CharField(max_length=255, verbose_name='URL')),
                ('response_status', models.CharField(max_length=255, verbose_name='response status')),
                ('response_body', models.CharField(max_length=255, verbose_name='response body')),
                ('message', models.CharField(max_length=255, verbose_name='internal message')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.AlterModelOptions(
            name='pokemons',
            options={'verbose_name': 'Pokemon', 'verbose_name_plural': 'Pokemons'},
        ),
    ]
