# Generated by Django 4.0.6 on 2022-07-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_logs_alter_pokemons_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='internal message'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='request_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='response_body',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='response body'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='response_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='response status'),
        ),
    ]
