# Generated by Django 4.0.6 on 2022-07-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_alter_logs_response_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='response_body',
            field=models.TextField(blank=True, null=True, verbose_name='response body'),
        ),
    ]
